### ISSUE TITLE
trames mqtt mal faites

### ISSUE THREAD

**Issue by Overnuts** [xlyric/pv-router-esp32#11]
Bonjour Cyril, 
je viens de mettre a jour mon routeur avec le build de la st-valentin :-)

depuis, j'ai des erreurs domoticz comme celle là quasiment toutes les 10 secondes:
`mosquitto: Invalid/Unhandled data received! (Topic: domoticz/in, Message: { "idx" : temperature , "svalue" : "13.19)`
ca ressemble beaucoup à d'autres erreurs que j'avais de temps en temps (je t'avais fait un mail ;-) )

je suis toujours en "pré-prod", mon cumulus est toujours dans le carton, le dimmer aussi mais je l'ai allumé ce matin.
je me demandais si c'est pas le dimmer qui remontait des conneries, mais en désactivant le mqtt du routeur, je n'ai plus la trace.

je fouille un peu le source... des fois que je trouverais un truc

**Comment by xlyric** [comment]
effectivement, il y a un truc qui colle pas dans ce qui est remonté 
ça devrait être du type { "idx" : temperature , "svalue" : "13.19" } 
Je vais regarder si il y a un truc qui a bougé. 
c'est assez étrange.

**Comment by Overnuts** [comment]
d'autant qu'on devrait meme avoir "1104"  au lieu de "temperature"  
1104  etant mon index de temperature dans domoticz.
2 trucs me surprennent:
- 1104 est dans la config du dimmer, comment le routeur pourrait le connaitre
- je vois que la temperature est mise a jour avec des trames qui passent quand meme

je vois passer ça dans mqtt explorer
![image](https://user-images.githubusercontent.com/61836209/220143384-817b5941-35a6-4ec7-8ad3-e53f7fdeaa43.png)

**Comment by xlyric** [comment]
oula... pas faux... ça sens la ligne rajouté un peu n'importe comment XD 
le routeur récupère la température du dimmer par défaut 
et donc à un moment ou un autre renvois vers le MQTT l'info, 
pour Home assistant c'est utile, par contre aucun interet pour Domoticz 
je commence à avoir une idée d'où est le pb

**Comment by Overnuts** [comment]
une bonne tete de coupable cette ligne là: 
https://github.com/xlyric/pv-router-esp32/commit/96f84d9ecbc197bfae55093296ba67417325211e#diff-c68cb553fdff2d071bc56d1ae60d3fe47682bf0042f069f995b1fb39e884e57dR104
:-D

**Comment by Overnuts** [comment]
a chaque fois, je récupère le latest bin, 
j'ai mon vscode lancé, j'essye de builder... je reviens

**Comment by xlyric** [comment]
[firmware.zip](https://github.com/xlyric/pv-router-esp32/files/10785724/firmware.zip)
voilà

**Comment by Overnuts** [comment]
> [firmware.zip](https://github.com/xlyric/pv-router-esp32/files/10785724/firmware.zip) voilà

rho le cachotier :-)
![image](https://user-images.githubusercontent.com/61836209/220147676-1ca856f3-6fb9-49a2-8abd-3cc32cf56dae.png)

**Comment by Overnuts** [comment]
j'ai re pull, et build, mon bin fonctionne

**Comment by xlyric** [comment]
j'avais mis le firmware en zip ;) 
j'attends ton retour en tout cas

**Comment by Overnuts** [comment]
oui, mais comme ca, je sais le builder :-)
plus de messages depuis tout a l'heure 
on est bon !

**Comment by xlyric** [comment]
ça tombe bien comme ça tu pourras me proposer des modifs de code ;)
