### ISSUE TITLE
La page config.html ne se lance pas en mode AP - first install

### ISSUE THREAD

**Issue by RiCode31** [xlyric/pv-router-esp32#14]
Bonjour Cyril,
je viens de déposer sur mon ESP32 via le web installeur le code du PV-ROUTER, mais le mode AP n'affiche pas la page config (ni config-ap.html). Il telecharge la version compressé :( donc inutilisable.
Tests effectués sur SAFARI (Mac et iOS). Pas de windows sous la main.
Je ne pense pas que cela soit normale :(
Bonne journée,
Eric

**Comment by xlyric** [comment]
oui avais vu ça comme safari n est pas conforme aux normes web. Il réinterprète je ne sais comment le renommage qu il est pas sensé voir. 
le site indique à safari que le fichier est compressé ( compression HTTP ) par contre il semblerait qu'il ne l'interprète pas correctement. 
dans tous les cas, ça reste étrange comme sur chrome PC ça fonctionne ( ainsi que sur les tel portables ) 

tu as possibilité de voir au niveau de ton navigateur si c'est un code 404 qui remonte ou autre chose  ?

**Comment by xlyric** [comment]
au passage, 3 choses: 
- la version ESP32 ( donc sans TTGO ) n'est plus supporté
- il y a eu une mise à jour majeur mi Mars, ( os espressif 3.5 -> 6.x ) et il faut faire un erase flash avant de téléverser l'ensemble du code. sinon le filesystem n était plus accessible. 
- le mode AP n'est la que pour les démonstrations, le wifi se configure maintenant directement avec le sérial après la programmation ( ou par le site internet ) 
https://ota.apper-solaire.org/ota.php
https://ota.apper-solaire.org/documentation.php --> voir configuration du wifi

**Comment by RiCode31** [comment]
Ne concerne que Safari, la compression n’est effectivement pas interprétée correctement par Safari. Je ne peux (ou ne sais pas) récupérer la réponse (aucune trace dans les outils développeurs : inspecteur web). Il semble qu’il y ait une solution dans les infos retournées par le serveur, du moins sur les « gros » serveur web.
En passant par chrome/Firefox les modifications de paramètres sont opérationnels.

**Comment by xlyric** [comment]
a oui, j'avais oublié ce point... 
ça vient du réponse header que safari prends un peu bizarrement :  

Content-Disposition: inline; filename="index.html.gz"
Content-Encoding: gzip
Content-Length: 3890
Content-Type: text/html

du coup il cherche à appeler cette page "index.html.gz" , qui n'est pas affecté dans mon code. 
je vais rajouter juste config.html.gz et index.html.gz, ça sera dans la prochaine mise à jour
mais c'est un bug connu chez safari et donc faut prendre un vrai navigateur.

**Comment by xlyric** [comment]
j'ai peut être trouvé une autre astuce

**Comment by xlyric** [comment]
l'astuce ne marche pas. bug connu dans la librairie web pour ESP 
https://github.com/me-no-dev/ESPAsyncWebServer/issues/926#top
je peux rien faire

**Comment by xlyric** [comment]
peut être trouvé une autre astuce, j'ai modifié la librairie espasynwebserver
dans 
.pio\libdeps\ttgo-t-display\ESPAsyncWebServer-esphome\src\WebResponses.cpp

il faut commenter la ligne 538 et 569. 
si tu peux test pour me dire si c'est mieux

**Comment by RiCode31** [comment]
Ça marche la page apparait sur Safari (Chrome et Firefox) !
Quelques erreurs 404 de chargement de polices de font awesome (sur Safari, pas Chrome ni Firefox cache vidé) mais sans impact sur l'utilisation ni visible sur les pages web
fa-regular-400.svg#fontawesome
fa-regular-400.ttf
fa-regular-400.woff
fa-regular-400.woff2
good job !

**Comment by xlyric** [comment]
cool... c'est quand même étrange qu'ils aient pas vu ce bug dans la librairie web. 
comme quoi, personne n'utilise safari ... 
j'vais pousser la modif

**Comment by xlyric** [comment]
je viens de pousser le pull request chez l'éditeur
