### ISSUE TITLE
In case of wifi connection lost, no reconnection

### ISSUE THREAD

**Issue by TofMassilia13320** [xlyric/pv-router-esp32#22]
En coupant ma box internet ce matin, je me suis rendu compte que le router ne se reconnectait pas au SSID.
Bug dans wifi-connection.h ligne 76: C'est if (!AP) au lieu de if(AP).

**Comment by xlyric** [comment]
en principe c'est sensé le faire, avec un test toutes les 30 secondes.

**Comment by xlyric** [comment]
quand le SSID tombe, la variable passe en mode AP et il test la présence du SSID configuré sur le réseau ( -> search_wifi_ssid(); )
si c'est valable alors il y a une reconnexion.
la fonction a été testé par ceux qui avaient ce genre de problème suite coupure de courant et ça fonctionne très bien.

**Comment by TofMassilia13320** [comment]
J'avais pas capté que la variable passait à AP en cas de SSID down.

**Comment by TofMassilia13320** [comment]
J'avais pas capté que la variable passait à AP en cas de SSID down.
