### ISSUE TITLE
config-light.html is always loaded

### ISSUE THREAD

**Issue by TofMassilia13320** [xlyric/pv-router-esp32#24]
Since your merge of my last push, config-light.html is always loaded whatever the router version used (normal or light).
You performed merge wrongly.

Please recheck with my branch through webFunctions.h at following lines.

**l92**: compress_html(request,"/config-light.html.gz", "text/html");
shall be:
==>compress_html(request,"/**config.html.gz**", "text/html");

**l94**: compress_html(request,"/config-ap.html.gz", "text/html");
shall be:
==>compress_html(request,"/**config-light.html.gz**", "text/html");

**Comment by xlyric** [comment]
ça marche, je vais regarder

**Comment by xlyric** [comment]
c'est corrigé
