### ISSUE TITLE
Format Trames MQTT (compatibilité jeedom)

### ISSUE THREAD

**Issue by nmellado** [xlyric/pv-router-esp32#25]
Bonjour,

J'ai un soucis de connection MQTT avec Jeedom, broker Mosquitto (qui si j'ai bien suivi, supporte les trames v3.1 et +).
En regardant le source de ce projet, il semblerait que les trames MQTT émises sont en 2.5, est-ce bien le cas ?
J'ai un peu de mal à débuguer ma connection car rien ne sort dans la console série (onglet log sur la dashboard du router).

Version pvrouter: 20230630

Merci

PS: si je poste au mauvais endroit, ne pas hésiter à me re-router
PS2: je peux reformatter en anglais si besoin.

**Comment by xlyric** [comment]
Bonjour Antoine, 

c'est assez étrange que tu ai un problème sur les trames, 
elles sont envoyé avec la configuration par défaut fournis par la librairie et tous ceux qui utilisent mosquito (comme moi) n'ont pas constaté de problème. 
Il se passe quoi exactement coté mqtt ? 
pose la question sur le forum : https://forum-photovoltaique.fr/viewtopic.php?f=110&t=41777
