### ISSUE TITLE
le passage de DIMMERLOCAL à FALSE dans le fichier config.h empeche la compilation

### ISSUE THREAD

**Issue by multinet33** [xlyric/pv-router-esp32#38]
Ma config : TTGO pour PV ROUTER et DIMMER DISTANT le tout sur ENPAHSE v7

j'ai donc logiquement voulu passer DIMMERLOCAL à FALSE dans le config.h maisla compilation ne fonctionne pas car il y a des usage des constantes dans main.ccp et dans dimmerFunction.h sans tester la valeur de DIMMERLOCAL

**Comment by xlyric** [comment]
on y touche pas, il faudra que je vire la fonction, c'est directement dans la page de config.html que ça se joue. 
le dimmer local n'est actif que si on coche la case dans le formulaire.
