### ISSUE TITLE
Fontius ?

### ISSUE THREAD

**Issue by multinet33** [xlyric/pv-router-esp32#39]
Dans appweb.h

il y a la ligne suivante : 
 if ( Servermode == "frontius" ) {   configmodule.Fronius_present = !configmodule.Fronius_present; }

==> frontius est-ce correct ?

**Comment by xlyric** [comment]
ça devrait/pourrait effectivement être fronius, mais coté page web, ça n'est pas cablé. 

pour l'activer il faut dans tous les cas pousser à la main ( par VS ) le fichier de config du fronius. 
et l'activer par une commande HTTP

**Comment by xlyric** [comment]
j'ai corrigé la ligne pour éviter toute confusion
