### ISSUE TITLE
commit "conservation des consos"

### ISSUE THREAD

**Issue by Dom1066** [xlyric/pv-router-esp32#46]
bonjour, 
le commit "conservation des consos" me donne des remontées MQTT pv-router-xxx-grid bizzares.
![Capture PV router-grid](https://github.com/xlyric/pv-router-esp32/assets/125456511/b1ab131d-8541-4541-b983-d91ea0102d6e)

**Comment by xlyric** [comment]
il faut que je vois effectivement, comme en théorie il était sensé garder la conso déjà faite même après un reboot.

**Comment by xlyric** [comment]
ça dvrait être mieux, j'ai poussé un correctif

**Comment by xlyric** [comment]
je viens de trouver, j'ai fait de la merde j'ai poussé un mauvais fichier
