### ISSUE TITLE
Crash si SSID et pass sont vides

### ISSUE THREAD

**Issue by fcrozat** [xlyric/pv-router-esp32#47]
Firmware 20240316

Flash firmware PVRouteur complet
sur la console serie:
ssid (pas de ssid renseigné)
puis
pass (pas de mot de passe renseigné)
puis 
reboot

crash en boucle de l'application

**Comment by xlyric** [comment]
roo, je regarde ça demain, c'est sur que c'est pas une condition qui est standart

**Comment by xlyric** [comment]
ça sera corrigé dans la prochaine mise à jour
