### ISSUE TITLE
Classe incorrecte dans le reporting MTQQ sur Home Assistant

### ISSUE THREAD

**Issue by fcrozat** [xlyric/pv-router-esp32#48]
En regardant les logs de HA, j'ai noté le message suivant:

`Mar 19 07:24:32 xxxxx systemd-home-assistant[12208]: 2024-03-19 07:24:32.927 ERROR (MainThread) [homeassistant.components.mqtt.mixins] Error 'expected SensorDeviceClass or one of 'date', 'enum', 'timestamp', 'apparent_power', 'aqi', 'atmospheric_pressure', 'battery', 'carbon_monoxide', 'carbon_dioxide', 'current', 'data_rate', 'data_size', 'distance', 'duration', 'energy', 'energy_storage', 'frequency', 'gas', 'humidity', 'illuminance', 'irradiance', 'moisture', 'monetary', 'nitrogen_dioxide', 'nitrogen_monoxide', 'nitrous_oxide', 'ozone', 'ph', 'pm1', 'pm10', 'pm25', 'power_factor', 'power', 'precipitation', 'precipitation_intensity', 'pressure', 'reactive_power', 'signal_strength', 'sound_pressure', 'speed', 'sulphur_dioxide', 'temperature', 'volatile_organic_compounds', 'volatile_organic_compounds_parts', 'voltage', 'volume', 'volume_storage', 'volume_flow_rate', 'water', 'weight', 'wind_speed' for dictionary value @ data['device_class']' when processing MQTT discovery message topic: 'homeassistant/sensor/PvRouter-2D14/config', message: '{'device_class': '', 'unit_of_measurement': '', 'state_class': '', 'name': '-2D14', 'state_topic': 'homeassistant/sensor/PvRouter-2D14/state', 'availability_topic': 'homeassistant/sensor/PvRouter-2D14/status', 'unique_id': '2D14-', 'value_template': '{{ value_json. }}', 'command_topic': 'homeassistant/sensor/PvRouter-2D14/command', 'command_template': '{{ value_json. }}', 'expire_after': '60', 'device': {'identifiers': 'PvRouter-2D14', 'name': 'PvRouter-2D14', 'sw_version': 'PvRouter Version 20240316', 'model': 'ESP32 TTGO 192.168.1.27', 'manufacturer': 'Cyril Poissonnier', 'configuration_url': 'http://192.168.1.27'}, 'platform': 'mqtt'}'`

**Comment by xlyric** [comment]
je vois déjà des erreurs au niveau du nom 
unique_id': '2D14-',
'name': '-2D14',
et effectivement 'device_class': '' est vide 

je corrigerais

**Comment by xlyric** [comment]
Trouvé le problème, sera corrigé à la prochaine mise  jour
