### ISSUE TITLE
Micro bug : la version ne s'affiche pas sur la page d'acceuil PV routeur Firmware light 20240501

### ISSUE THREAD

**Issue by ciscolyon69** [xlyric/pv-router-esp32#49]
Salut,

J'ai détecté un microbug sur la version PV routeur Firmware **light** 20240501

La version ne s'affiche pas sur la page d’accueil (pas de problème sur config.html)
(pas de problème sur la version normale)
![image](https://github.com/xlyric/pv-router-esp32/assets/123967877/50cc8026-b3fa-404a-ab04-d939417dd041)

Bernex sur le forum

**Comment by xlyric** [comment]
je vais corriger aussi

**Comment by xlyric** [comment]
c'est corrigé et amélioré

**Comment by ciscolyon69** [comment]
merci je maj quant je vais chez mon voisin
