### ISSUE TITLE
Disabling mqtt to homeassistant

### ISSUE THREAD

**Issue by Overnuts** [xlyric/pv-router-esp32#8]
Hi Cyril, 
I saw a lot of mqtt traffic to topic "homeassistant/sensor"
Would it be possible to add a checkbox in config to disable this ?
thanks for your work

**Comment by xlyric** [comment]
Salut, 
oui, c'est possible, c'est pas une mauvaise idée. 
effectivement pour ceux sous jeedom ou domoticz, ça fait du traffic en plus
Je fais ça pour le prochain push

**Comment by Overnuts** [comment]
but alors you are french :-)

**Comment by xlyric** [comment]
et ouai !! 
c'est fait, je viens de pousser la mise à jour.
et dispo en OTA 
https://ota.apper-solaire.org/ota.php
