### ISSUE TITLE
error name file in include

### ISSUE THREAD

**Issue by Benoit485** [xlyric/pv-router-esp32#9]
Hey

Have error with name file in include (maybe is work on your environment but not my debian, for you have no error ?)

File : /src/functions)/dallasFunction.h

in main.cpp include for dallasfunction.h without uppercase for F

If this can help some

**Comment by xlyric** [comment]
Hi, 
Thank, I have just make the correction

TY. 

you can use OTA site for update the code
https://ota.apper-solaire.org/ota.php
